- name: "Install common packages"
  hosts: newengagefront1
  become: yes
  become_method: sudo

  tasks:

    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: Get Node.js v8 setup script
      shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -

    - name: Install Node.js  
      shell: apt-get install -y nodejs

    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - htop
        - jq
        - dos2unix
        - git-core
        - python-software-properties

    - name: Modify /etc/pam.d/common-session and add a line (only if it doesn't exist)
      shell: grep -q -F 'session required                        pam_limits.so' /etc/pam.d/common-session || echo 'session required                        pam_limits.so' >> /etc/pam.d/common-session

    # Set vm.zone_reclaim_mode = 0
    - sysctl:
        name: vm.zone_reclaim_mode
        value: 0
        state: present

    # Set net.ipv4.tcp_tw_reuse = 1
    - sysctl:
        name: net.ipv4.tcp_tw_reuse
        value: 1
        state: present

    # Set net.ipv4.ip_local_port_range = 1024 65023
    - sysctl:
        name: net.ipv4.ip_local_port_range
        value: "1024 65023"
        state: present
    
    # Set net.ipv4.tcp_max_syn_backlog = 10240
    - sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: 10240
        state: present

    # Set net.ipv4.tcp_max_tw_buckets = 400000
    - sysctl:
        name: net.ipv4.tcp_max_tw_buckets
        value: 400000
        state: present
    
    # Set net.ipv4.tcp_max_orphans = 60000
    - sysctl:
        name: net.ipv4.tcp_max_orphans
        value: 60000
        state: present

    # Set net.ipv4.tcp_synack_retries = 3
    - sysctl:
        name: net.ipv4.tcp_synack_retries
        value: 3
        state: present

    # Set fs.file-max = 1048576 
    - sysctl:
        name: fs.file-max
        value: 1048576
        state: present

    # Set net.core.somaxconn = 10000
    - sysctl:
        name: net.core.somaxconn
        value: 10000
        sysctl_set: yes
        state: present
        reload: yes

    - pam_limits:
        domain: root
        limit_type: soft
        limit_item: nofile
        value: 1048576

    - pam_limits:
        domain: root
        limit_type: hard
        limit_item: nofile
        value: 1048576

    - pam_limits:
        domain: '*'
        limit_type: soft
        limit_item: nofile
        value: 1048576

    - pam_limits:
        domain: '*'
        limit_type: hard
        limit_item: nofile
        value: 1048576

    - name: Making /mnt/ephemeral directory
      file: path=/mnt/ephemeral/ state=directory


